name: Build and Push Apptainer Image to GHCR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: R_4_4
      REGISTRY: ghcr.io

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with: 
          apptainer-version: 1.3.6

      - name: Log in to GitHub Container Registry
        run: |
          echo "${{ secrets.PAT }}" | apptainer remote login \
            -u "${{ github.actor }}" --password-stdin "oras://${{ env.REGISTRY }}"

      - name: Build Apptainer Image
        run: |
          # Replace 'image.def' with the actual path to your definition file
          apptainer build "${{ env.IMAGE_NAME }}.sif" r_4_4.def

      - name: Push to GHCR
        run: |
          # Convert owner name to lowercase for the registry URL
          OWNER_LOWER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          
          apptainer push "${{ env.IMAGE_NAME }}.sif" \
            "oras://${{ env.REGISTRY }}/${OWNER_LOWER}/${{ env.IMAGE_NAME }}:latest"
